language: php

php:
  - 7.2
  - 7.3
  - 7.4snapshot
  - nightly

matrix:
  allow_failures:
  - php: 7.4snapshot
  - php: nightly

env:
  - COMPOSER_OPTS=""
  - COMPOSER_OPTS="--prefer-lowest"

install:
  - composer update $COMPOSER_OPTS

script:
  - vendor/bin/phpunit

jobs:
  include:
    - stage: dependency checks
      script:
        - vendor/bin/composer-require-checker
    - stage: static analysis
      script:
        - vendor/bin/phpstan analyse --level=max src
        - vendor/bin/phpstan analyse --configuration=phpstan-tests.neon --level=max tests
    - stage: coding standards
      script:
        - vendor/bin/phpcs --standard=phpcs.xml src tests
    - stage: coverage
      script:
        - vendor/bin/phpunit --coverage-clover=coverage.xml
        - bash <(curl -s https://codecov.io/bash)

git:
  depth: 5

group: travis_latest
